services:
  - type: web
    name: mern-ecommerce-frontend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18

    autoDeploy: true
    rootDir: client

  - type: web
    name: mern-ecommerce-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        value: mongodb+srv://apawar0078:V3gCHUUHjbsLa3aH@cluster0.tmjjcxi.mongodb.net/shopping-cart?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: mysecretkey
      - key: STRIPE_KEY
        value: sk_test_51RTLScSHln5hqfkmcSE4QaRLnjPWjubyyCevMagqb7WIYaoRAINVsE40gxfVMcgjh9DDf2JUtwiGvZsl5A1BGavL00MmvV49MK  
    autoDeploy: true
    rootDir: server