  - type: web
    name: shopping-site-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    rootDir: shopping-site-backend
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        value: mongodb+srv://apawar0078:V3gCHUUHjbsLa3aH@cluster0.tmjjcxi.mongodb.net/shopping-cart?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: mysecretkey
      - key: STRIPE_KEY
        value: sk_test_51RTLScSHln5hqfkmcSE4QaRLnjPWjubyyCevMagqb7WIYaoRAINVsE40gxfVMcgjh9DDf2JUtwiGvZsl5A1BGavL00MmvV49MK
      - key: NODE_ENV
        value: production
      - key: CLOUD_NAME
        value: dregk7i5v
      - key: CLOUD_API_KEY
        value: 528236516363663
      - key: CLOUD_API_SECRET
        value: t5VTbW5cm7uf5ilx_bx9-YJDVow
      - key: CLIENT_URL
        value: http://localhost:5173